<script type="text/javascript" src="<?php echo $_assets_url; ?>/js/vendor/jquery/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $_assets_url; ?>/js/vendor/uikit/uikit.min.js"></script>
<script type="text/javascript" src="<?php echo $_assets_url; ?>/js/bootstrap.js"></script>
<script type="text/javascript" src="<?php echo $_assets_url; ?>/js/LC.js"></script>
<script type="text/javascript" src="<?php echo $_assets_url; ?>/js/functions.js"></script>
<script type="text/javascript" src="<?php echo $_assets_url; ?>/js/dbfunctions.js"></script>
<script type="text/javascript" src="<?php echo $_assets_url; ?>/js/app.js.js"></script>
